set -g mouse on
set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

set -g status-left ""
set -g status-left-length 0
set -g status-right "\"#{pane_title}\" (#W) [#S]"
set -g status-right-length 120
set -g window-status-format " #I:#{=25:pane_title}#F "
set -g window-status-current-format " #I:#{=25:pane_title}#F "
set -g window-status-current-style "bg=colour173,fg=black,bold"
