set -g mouse on
set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

bind -T copy-mode-vi WheelUpPane   select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 2 scroll-down
bind -T copy-mode    WheelUpPane   select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode    WheelDownPane select-pane \; send-keys -X -N 2 scroll-down

set -g status-left ""
set -g status-left-length 0
set -g status-right "\"#{pane_title}\" (#W) [#S]"
set -g status-right-length 120
set -g window-status-format " #I:#{=25:pane_title}#F "
set -g window-status-current-format " #I:#{=25:pane_title}#F "
set -g window-status-current-style "bg=colour173,fg=black,bold"
